[build]
  base = "frontend"
  publish = ".next"
  command = "npm run build"

[build.environment]
  PYTHON_VERSION = "3.12"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  directory = "../netlify/functions"
